### ISSUE TITLE
Failed build, uncertain what what /internal/modules/cjs/loader.js:583 is

### ISSUE THREAD

**Issue by thor314** [rocket-pool/rocketpool#152]
ran npm && npm test. Got the following error. Uncertain what to try.
I’m on a rasperry pi 4b w/ debian OS.
```

Starting our own Ganache instance
Starting our own beacon chain simulator instance
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'typedarray-to-buffer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/thormisc/rocketpool/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error: Cannot find module 'typedarray-to-buffer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/thormisc/rocketpool/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/thormisc/rocketpool/node_modules/web3-providers-ws/node_modules/websocket/lib/websocket.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/thormisc/rocketpool/node_modules/web3-providers-ws/node_modules/websocket/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
Truffle v5.0.1 (core: 5.0.1)
Node v10.15.2
npm ERR! Test failed.  See above for more details.
```

**Comment by darcius** [comment]
Hey @thor314, sorry for the delay mate, we were at Devcon all the last week.

Just tested it out on my Pi 4GB and got the same issue, looks like a common dependency is missing for some reason, so I've added it to the npm manifest. You can run `git pull` again, then `npm install && npm test` and it should run.

Keep in mind these tests are quite extensive and took my Pi about 24 mins to run in total. My desktop by comparison takes about 2 mins. You might wanna grab a drink or two while they're running ;)
