### ISSUE TITLE
Wallet test-recovery: panic: runtime error: slice bounds out of range [:4] with length 3

### ISSUE THREAD

**Issue by jpenglert** [rocket-pool/rocketpool#259]
Running rocket pool `1.6.3` on Ubuntu.

Repro:

1. `rocketpool wallet t`
2. Enter `24`
3. Enter `asdf` for "Word Number 1"
4. panic: runtime error: slice bounds out of range....

Example:

```
$ rocketpool wallet t

NOTE:
This command will test the recovery of your node wallet's private key and (unless explicitly disabled) the validator keys for your minipools, but will not actually write any files; it's simply a "dry run" of recovery.
Use `rocketpool wallet recover` to actually recover the wallet and validator keys.

Please enter the number of words in your mnemonic phrase (24 by default):
24

Enter Word Number 1 of your mnemonic:

panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
github.com/rocket-pool/smartnode/rocketpool-cli/wallet/bip39.(*MnemonicValidator).AddWord(0xc00013fd98, {0xc00041c320, 0x4})
	/smartnode/rocketpool-cli/wallet/bip39/mnemonic-validator.go:36 +0x22f
github.com/rocket-pool/smartnode/rocketpool-cli/wallet.promptMnemonic()
	/smartnode/rocketpool-cli/wallet/utils.go:69 +0x27f
github.com/rocket-pool/smartnode/rocketpool-cli/wallet.testRecovery(0xc000131760)
	/smartnode/rocketpool-cli/wallet/test.go:45 +0x179
github.com/rocket-pool/smartnode/rocketpool-cli/wallet.RegisterCommands.func5(0xc000131760)
	/smartnode/rocketpool-cli/wallet/commands.go:192 +0x94
github.com/urfave/cli.HandleAction({0x9f9f80?, 0xc6ba88?}, 0xd?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0xabb47a, 0xd}, {0x0, 0x0}, {0xc0003f8b90, 0x1, 0x1}, {0xaf33a9, 0x8f}, {0xad7904, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x65b
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000182700, 0xc0001314a0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x91b
github.com/urfave/cli.Command.startApp({{0xab2d4e, 0x6}, {0x0, 0x0}, {0xc0003f8b40, 0x1, 0x1}, {0xac36b5, 0x16}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e7
github.com/urfave/cli.Command.Run({{0xab2d4e, 0x6}, {0x0, 0x0}, {0xc0003f8b40, 0x1, 0x1}, {0xac36b5, 0x16}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x825
github.com/urfave/cli.(*App).Run(0xc000182540, {0xc000022180, 0x3, 0x3})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.main()
	/smartnode/rocketpool-cli/rocketpool-cli.go:166 +0xd67
```

**Comment by wallnerhaas** [comment]
Setting up my first Rocket Pool node and just arrived at the "Setting up Wallet" section and I'm encountering the same issue.
I created a new wallet and generated the seed with `rocketpool wallet init` . When I tried to enter word number 2, I received the same error. Now I'm confused on how to proceed - should I generate a new seed or can I use the seed I initially created?

I tried the above `rocketpool wallet t` command and was able to enter my seed and receive a "Node Account" address and the message that "No validator keys were found".

**Comment by 0xfornax** [comment]
Fixed by https://github.com/rocket-pool/smartnode/pull/303
